import blurMap from "@/content/generated/blur.json";

const map = blurMap as Record<string, string>;

/**
 * Returns `placeholder`/`blurDataURL` props for a <Image> given a public image
 * path like "/images/hero-children.webp". The blur data is generated by the
 * media pipeline (scripts/optimize-media.mjs). Falls back to no placeholder if
 * a blur wasn't generated for the asset.
 */
export function blurProps(src: string): {
  placeholder?: "blur";
  blurDataURL?: string;
} {
  const key = src.replace(/^\/images\//, "").replace(/\.[a-z0-9]+$/i, "");
  const blurDataURL = map[key];
  return blurDataURL ? { placeholder: "blur", blurDataURL } : {};
}
